import React from "react";

const Lorem = () => {
    return (
        <div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Scelerisque fermentum dui faucibus in ornare quam. Semper quis lectus nulla at. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget. Iaculis urna id volutpat lacus. Aliquam sem et tortor consequat id porta nibh. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Porta non pulvinar neque laoreet suspendisse interdum consectetur libero id. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Orci ac auctor augue mauris augue neque. A diam maecenas sed enim ut sem viverra aliquet. Interdum velit euismod in pellentesque. Interdum posuere lorem ipsum dolor. Ornare lectus sit amet est placerat in egestas. Elementum sagittis vitae et leo duis ut. Egestas tellus rutrum tellus pellentesque eu. Cras adipiscing enim eu turpis egestas pretium aenean pharetra. Id consectetur purus ut faucibus pulvinar elementum integer.</p>
            <p>Odio eu feugiat pretium nibh ipsum. Tellus orci ac auctor augue mauris. Ultrices sagittis orci a scelerisque. In metus vulputate eu scelerisque felis imperdiet proin fermentum. Commodo odio aenean sed adipiscing. Lacus vel facilisis volutpat est velit. Vitae purus faucibus ornare suspendisse sed. Nunc mattis enim ut tellus elementum sagittis vitae et leo. Tellus in hac habitasse platea dictumst vestibulum rhoncus est. Volutpat diam ut venenatis tellus in metus vulputate eu scelerisque. Vitae suscipit tellus mauris a diam maecenas. Dui vivamus arcu felis bibendum ut tristique et egestas quis. Ipsum a arcu cursus vitae congue mauris rhoncus. Erat nam at lectus urna duis convallis convallis tellus id.</p>
            <p>Pellentesque diam volutpat commodo sed. Lorem sed risus ultricies tristique. Sit amet nulla facilisi morbi. Vitae justo eget magna fermentum iaculis eu non diam. Id faucibus nisl tincidunt eget nullam non. Senectus et netus et malesuada fames ac turpis egestas. Nullam ac tortor vitae purus. Platea dictumst quisque sagittis purus sit amet volutpat consequat. Quis eleifend quam adipiscing vitae proin sagittis. Elit eget gravida cum sociis. A diam maecenas sed enim. Urna id volutpat lacus laoreet non curabitur gravida arcu. Ornare arcu odio ut sem nulla pharetra. Lectus nulla at volutpat diam ut. Sit amet consectetur adipiscing elit pellentesque habitant.</p>
        </div>
    )
}

export { Lorem }